```{r}
library(xgboost)
library(tidyverse)
library(readxl)    
library(magrittr)
```

```{r}
file_path <- "/Users/mo/Desktop/Data Mining/Data-Mining-Project/Data/Latest Reported Events (4).xlsx"
diseaseInfo <- read_excel(file_path)
head(diseaseInfo)

```

```{r}
set.seed(1234)
diseaseInfo <- diseaseInfo[sample(1:nrow(diseaseInfo)), ]
```

```{r}
diseaseInfo_humansRemoved <- diseaseInfo %>%
    select(-starts_with("human"))
diseaseLabels <- diseaseInfo %>%
    select(humansAffected) %>%  
    is.na() %>%             
    magrittr::not()
head(diseaseLabels)     
head(diseaseInfo$humansAffected) 

```

```{r}
head(diseaseInfo$country)
region <- model.matrix(~country-1, diseaseInfo)
diseaseInfo_numeric$is_domestic <- str_detect(diseaseInfo$speciesDescription, "domestic")
speciesList <- diseaseInfo$speciesDescription %>%
  str_replace_all("[[:punct:]]", "") %>% 
  str_extract("[a-z]*$")
speciesList <- tibble(species = speciesList)
options(na.action='na.pass')
species <- model.matrix(~species-1, speciesList)
diseaseInfo_numeric <- cbind(diseaseInfo_numeric, region, species)
diseaseInfo_matrix <- data.matrix(diseaseInfo_numeric)
```

```{r}
numberOfTrainingSamples <- round(length(diseaseLabels) * 0.7)

train_data <- diseaseInfo_matrix[1:numberOfTrainingSamples, ]
train_labels <- diseaseLabels[1:numberOfTrainingSamples]

test_data <- diseaseInfo_matrix[-(1:numberOfTrainingSamples), ]
test_labels <- diseaseLabels[-(1:numberOfTrainingSamples)]
```

```{r}
dtrain <- xgb.DMatrix(data = train_data, label = train_labels)
dtest <- xgb.DMatrix(data = test_data, label = test_labels)
```

```{r}
model <- xgboost(data = dtrain,   
                 nrounds = 2, 
                 objective = "binary:logistic") 
```

```{r}
pred <- predict(model, dtest)

err <- mean(as.numeric(pred > 0.5) != test_labels)
print(paste("test-error =", err))
```

```{r}
model_tuned <- xgboost(data = dtrain,         
                       max.depth = 3, 
                       nround = 2, 
                       objective = "binary:logistic") # the objective function 
pred <- predict(model_tuned, dtest)
err <- mean(as.numeric(pred > 0.5) != test_labels)
print(paste("test-error=", err))

```

```{r}
negative_cases <- sum(train_labels == FALSE)
positive_cases <- sum(train_labels == TRUE)

model_tuned <- xgboost(data = dtrain,           
                       max.depth = 3, 
                       nround = 10,
                       early_stopping_rounds = 3, 
                       objective = "binary:logistic",
                       scale_pos_weight = negative_cases / positive_cases)
pred <- predict(model_tuned, dtest)
err <- mean(as.numeric(pred > 0.5) != test_labels)
print(paste("test-error=", err))

```

```{r}
model_tuned <- xgboost(data = dtrain,  
                       max.depth = 3, 
                       nround = 10, 
                       early_stopping_rounds = 3, 
                       objective = "binary:logistic",
                       scale_pos_weight = negative_cases / positive_cases,
                       gamma = 1) 
pred <- predict(model_tuned, dtest)
err <- mean(as.numeric(pred > 0.5) != test_labels)
print(paste("test-error=", err))

```

```{r}
xgb.plot.multi.trees(feature_names = colnames(diseaseInfo_matrix), 
                     model = model_tuned)
odds_to_probs <- function(odds){
    return(exp(odds) / (1 + exp(odds)))
}
odds_to_probs(-0.599)
importance_matrix <- xgb.importance(colnames(diseaseInfo_matrix), model = model_tuned)
xgb.plot.importance(importance_matrix)
```

